steps:
  - name: hashicorp/terraform:light
    args:
      - init
  - name: hashicorp/terraform:light
    args:
      - apply
      - -auto-approve
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
